### ISSUE TITLE
Request: un-protect ProblemResults._compute_mean_G

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#100]
I wanted to calculate the Andrews, Gentzkow and Shapiro sensitivity matrix from my PyBLP estimates, and it looks like the matrix they call G (derivative of average sample moments with respect to parameters) is not saved anywhere, but can easily be computed with the protected method `ProblemResults._compute_mean_G()`.

First, is my understanding correct?

Second, in the event other people want to do the same calculation, would it be possible to make `_compute_mean_G` public and documented?

**Comment by jeffgortmaker** [comment]
Yes, that method computes the `G` that you're looking for. You should be able to use it without any issues other than a well-justified aversion to not using private methods.

And yes -- I'll keep this issue open as a reminder to create a `ProblemResults.moment_jacobian` attribute, since we're already computing it. Thanks for the suggestion!
