### ISSUE TITLE
Question about fixed effects absorption

### ISSUE THREAD

**Issue by pp2382** [jeffgortmaker/pyblp#102]
Hi Jeff and Chris,

Thanks so much for the public good you created. I had a question related to the methodology more than the code per se, I hope GitHub is still the right place to ask.

My question relates to how you deal with a large set of fixed effects in BLP. I think you guys are the first to document this and so I had a specific question on the use of Frisch-Waugh.
So, after having obtained $\delta$ from the contraction, you regress it on the set of X (possibly instrumented by Z) and a set of fixed effects. To avoid LSDV, you can apply Frisch-Waugh by demeaning $\delta$, X and Z and obtain $\hat\beta$ and $\hat\xi$, the residuals, with 2SLS.
So far so good. However, when you construct your objective function $\xi' Z W Z' \xi$, do you use the demeaned version of Z? That seems to be the right way to do it but I was unsure when reading your documentation. An alternative would be use the non-demeaned version of Z, but that would seem inconsistent with the previous step that account for the fixed effects through the demeaning.
A follow-up question relates to the gradient of this objective function: if $\delta$ and Z are demeaned to obtain the residuals and construct the objective function, does it mean that the derivative of $\delta$ should be demeaned as well?

I hope my question is not too confusing. Happy to clarify if needed.
Thanks so much,
Paul

**Comment by jeffgortmaker** [comment]
To answer your first question, yes -- we use demeaned instruments when constructing the objective function.

The de-meaning of the Jacobian is actually pretty interesting. You're right to note that since we demean delta when computing the objective, we need (at first glance) to demean its Jacobian when computing the gradient. Fortunately, it turns out that demeaning doesn't matter when computing the gradient! The math is involved, but it comes down to an orthogonality condition. I'll point you to footnote 103 in the appendix of [our paper](https://jeffgortmaker.com/files/pyblp.pdf).

As a side note, if you're asking these questions because you're implementing something similar on your own, some unsolicited advice is to write unit tests. As your questions make clear, the code for absorbing fixed effects can be subtle/nontrivial. Because of this, we have [unit tests](https://github.com/jeffgortmaker/pyblp/blob/86954d746981085e3da1d98997ce3d5a9997a396/tests/test_blp.py#L267) that verify results are pretty much the same, regardless of whether we absorb fixed effects or include indicator variables.

**Comment by pp2382** [comment]
Thanks Jeff for your answer! That makes total sense.

I am curious about your tests: in your simulations, do you find that absorbing the fixed effects is equivalent to adding dummy variables in your matrix? or does it give you roughly similar results? If there is no equivalence, is it due to the approximation when demeaning the fixed effects or from the fact that Frisch-Waugh does not exactly apply to nonlinear GMM?
No worries if you haven't explored these questions, I am just curious.

Thanks again for your reply.

**Comment by jeffgortmaker** [comment]
Great! My sense is that up to numerical error, absorbing fixed effects is equivalent to including dummies.

Small numerical differences will come from a number of places. Especially when there are multiple levels of fixed effects, absorbing them is done with a small amount of numerical error. And when fixed effects aren't absorbed, inverting matrices of dummy variables creates its own small numerical error. As optimization proceeds, these errors slowly compound into something that can be somewhat nontrivial.

For example, in our unit tests (9 different simulations x 7 fixed effect configurations), estimating each model with fixed effect absorption and dummy variables leads to estimates (parameters, standard errors, delta, costs, xi, omega, Jacobians, objective, gradient) that are [equal](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) up to an absolute tolerance of 1e-8 and a relative tolerance of 1e-5. And if I remember correctly while writing the unit test, it's precisely the configurations where we expect more numerical error (multiple levels of fixed effects, more objective iterations, etc.) where these tolerances are almost binding.

That said, there's always a chance (especially with new features that we're adding) that things aren't theoretically equivalent. Hopefully this type of unit test (or our own analytic calculations) will catch them, but it's always possible that there's a bug! So far things look equivalent.

**Comment by pp2382** [comment]
Thanks for the infos. It's reassuring to know that the two methods deliver the same results.
Paul
