### ISSUE TITLE
Simulating Problem via R + reticulate

### ISSUE THREAD

**Issue by clukewatson** [jeffgortmaker/pyblp#106]
Howdy, 

I hope this is a layup for you guys. I have been successful at solving problems using R+reticulate. I now need to do a Monte Carlo study, so I tried to implement the tutorial problem... and I immediately failed when trying to set up the product data / building ID inputs. I have googled the errors (not really any help) and I have tried various permutations of how to enter the command (many more than what I have below), but I have not progressed after about two hours. 

I would appreciate any help. Please let me know if you'd like more information

```
# target: id_data = pyblp.build_id_data(T=50, J=20, F=10)

id_data <- pyblp$build_id_data(T=50, J=20, F=10)
#  Error in py_call_impl(callable, dots$args, dots$keywords) : 
#  ValueError: Both T and F must be positive ints. 

id_data <- pyblp$build_id_data(T=50L, J=20L, F=10L)
# Error in py_ref_to_r(x) : 
#  Conversion from numpy array type 20 is not supported
```

Other info:
```
library(tidyverse)
library(reticulate)
pyblp <- import("pyblp")
# utilities
np <- import("numpy")
scipy <- import("scipy")
sympy <- import("sympy")
patsy <- import("patsy")
```

**Comment by clukewatson** [comment]
(1) I can successfully run "id_data =pyblp.build_id_data(T=50,J=20,F=10)" via Jupyter / IPython

(2) I can successfully run the following in R/Rstudio 
```
problem <- pyblp$Problem(
  product_formulations = tuple(
    pyblp$Formulation("1 + hpwt + air + mpd + space") # Linear demand
    , 
    pyblp$Formulation("1 + prices + hpwt + air + mpd + space") # Nonlinear demand
    # , 
    # pyblp$Formulation("1 + log(hpwt) + air + log(mpg) + log(space) + trend") # Supply
  ),
  agent_formulation = pyblp$Formulation("0 + I(1 / income)"), # Price interaction
  # costs_type = "log", # Log-linear costs
  product_data = read_csv(pyblp$data$BLP_PRODUCTS_LOCATION),
  agent_data = read_csv(pyblp$data$BLP_AGENTS_LOCATION)
)
problem


results <- problem$solve(
  sigma = diag(c(3.6, 0, 4.6, 1.8, 1, 2)), # Starting values for unobserved heterogeneity
  pi = rbind(0, -43.5, 0, 0, 0, 0),      # Starting value for the term on price
  initial_update = TRUE,                   # Update weight matrix at starting values
  # costs_bounds = tuple(0.001, NULL),       # Constrain marginal costs to be positive
  W_type = "clustered",                    # Cluster by automobile model
  se_type = "clustered"
)
results
```

**Comment by jeffgortmaker** [comment]
Since everything else works, I think this is an issue with reticulate, and one with a thankfully straightforward solution.

You solved your first issue correctly by using `L` to denote an int. The second error message is sort of opaque, but the issue there isn't with passing an integer as an argument, but rather with converting what's returned (a numpy structured array) into an object that R can handle. Reticulate just doesn't handle numpy structured arrays at the moment.

Instead, what you can do is `pyblp <- import("pyblp", convert=FALSE)` when importing pyblp. Then, reticulate won't automatically attempt to convert Python objects to their R equivalents.

When you then run `id_data <- pyblp$build_id_data(T=50L, J=20L, F=10L)` you shouldn't get an error, but you'll be stuck with a non-R object in `id_data`. If you try to execute `py_to_r(id_data)`, you'll get the same error as before.

What you need to do is convert `id_data` to a format that `py_to_r` can handle. For example, `py_to_r(pyblp$data_to_dict(id_data))` should give you something usable -- the R equivalent of a dictionary mapping structured array field names to values.

**Comment by clukewatson** [comment]
Thanks, @jeffgortmaker! I was able to figure it out a solution:
```
py_id_data <- py_to_r(pyblp$data_to_dict(pyblp$build_id_data(T=50L, J=20L, F=10L)))
df.py_id_data <- data.frame(market_ids = unlist(py_id_data$market_ids),
           firm_ids = unlist(py_id_data$firm_ids))
``` 
then one can pass **df.py_id_data** into **Simulation**.

I'm still playing with the simulation options. Once I get a full example set, I'll post it here for others. 

Thanks again.

**Comment by jeffgortmaker** [comment]
Great! Note that you can also pass the non-converted `id_data` directly to simulation. For example, the following works:

```python
library(reticulate)
pyblp <- import("pyblp", convert=FALSE)
id_data <- pyblp$build_id_data(T=50L, J=20L, F=10L)
integration <- pyblp$Integration('product', 9L)
simulation = pyblp$Simulation(
    product_formulations=c(
        pyblp$Formulation('1 + prices + x'),
        pyblp$Formulation('0 + x'),
        pyblp$Formulation('0 + x + z')
    ),
    beta=c(1, -2, 2),
    sigma=1,
    gamma=c(1, 4),
    product_data=id_data,
    integration=integration,
    seed=0L
)
```

You might want to do something like what you did above if you wished to, e.g., add additional fields to the product data before passing it do `Simulation`.

I'm going to close this issue for now, but please do post your full example when you finish it! It'll be really helpful for others.
