### ISSUE TITLE
Simulated prices after cost decrease

### ISSUE THREAD

**Issue by mas0088** [jeffgortmaker/pyblp#116]
Hi. Thank you for the great repo.

I was able to estimate the marginal costs using this repository. Let's assume the data covers 20 years and I would like to understand what will happen to prices if some firms have a 10% cost decrease starting in year 11. Will the simulation package support this kind of analysis? If yes, any brief guide will be highly appreciated. 

Thank you

**Comment by mas0088** [comment]
Thank you Jeff.  

It means that if I just estimate the marginal costs using 

mc = ProblemResults.compute_costs() 

and give these estimated costs (without any change) to 

ProblemResults.compute_prices(costs = mc) 

I should just get exactly my initial prices, right?

**Comment by jeffgortmaker** [comment]
Yes, I think that's right -- there might be some small differences because of numerical error, but you should pretty much get your prices back if you don't modify the marginal cost estimates.

Take a look at the linked docs! The prices argument specified the starting values, and you can use the iteration argument to specify a non-default iteration configuration with a different termination tolerance.

**Comment by mas0088** [comment]
Great. Thank you.
