### ISSUE TITLE
Supply-Side and Excluded Instruments

### ISSUE THREAD

**Issue by mtvseven** [jeffgortmaker/pyblp#124]
I have a question that is more theoretical than programming-related regarding the implementation of the supply side.

The data I have is transaction-level data on both products being sold and some information on customers from an online retailer. In order to familiarize myself with the mechanics of your package, I estimated the plain logit, am now adding a supply side without random coefficients, and will add random coefficients in the near future.

I have full visibility into cost data, so for plain logit I used wholesale price (one of the firm's input prices) as an excluded instrument for price. For supply I am wondering if it makes theoretical sense to include wholesale price as both an excluded demand_instruments and as a cost shifter in X3 or if you know of any theoretical issues this would cause even if the optimization routine converges without issues?

Thanks!

**Comment by chrisconlon** [comment]
Yes, you can use some marginal cost shifter such as wholesale price in two
places:

1. As a demand_instrument  z_{jt}^d
2. In the supply side since you are specifying mc_jt = w_jt * gamma +
\omega_{jt} in the X3 formula.

The main extra benefit from specifying supply in addition to just including
a strong cost shifter in z_{jt}^d is that you are also specifying the
conduct of the price setting firms. That is you are imposing the
constraint MR = MC once you specify a supply side (and X3 formula). You can
either specify the firm_ids or a full ownership matrix. Obviously this is a
strong (but powerful) assumption, and it is stronger than simply saying
"here is something correlated with prices but not the demand shock".


-Chris

**Comment by mtvseven** [comment]
Awesome, thank you!
