### ISSUE TITLE
Question: Constructing agent data from survey data

### ISSUE THREAD

**Issue by ny1526** [jeffgortmaker/pyblp#129]
Hi Jeff,

Thank you for this incredible resource. I have a question that is likely very simple, for which I apologize in advance.

I am having trouble understanding how exactly to construct agent data using survey data for which I have with demographics of individuals. I think this is related to Issue #63, but I am not sure.

I want to include 3 demographic characteristics in my model. All of them are binary (e.g., kids/no kids, high-skill/low-skill, higher education/no higher education). I have survey data where for each individual I observe all three of their demographics. However, for many markets I only have a few individuals in the survey for that market.

How do I construct the agent data for this? From the documentation, I think the first step is to call `pyblp.build_integration` for each market to construct the weights and nodes by market, but from there on I am a bit lost.

Thanks for the help.

**Comment by jeffgortmaker** [comment]
If you don't have any unobserved heterogeneity, you don't have to worry about #63 yet.

In each market, your agent data will have 5 columns: `market_ids`, `weights`, `kids`, `high_skill`, and `higher_education`. There will be 2 * 2 * 2 = 8 rows, if there are people in the population in each possible combination of these three variables. The `market_ids` column will just be an ID for that market. The `weights` column will be the share of the population with that row's demographics.

If you want to add unobserved heterogeneity, you'll add `nodes0`, `nodes1`, ... up to as many dimensions as you want. If you want to use quadrature, you can use the suggestions in #63.

Another thing to note is that in these types of models, you really want your demographic shares to be estimated without a lot of noise. So something like the true share of people with those demographics in the market. If you're really concerned about noise in your demographic estimates, you should probably do something like a nonparametric bootstrap, re-drawing your product data and individuals to construct your demographic shares a number of times, and re-estimating the model each time, to account for sampling error in how you estimate your demographic shares.

Does that help?

**Comment by ny1526** [comment]
Thanks so much for the quick response, this is really helpful. I would like to incorporate unobserved heterogeneity, so the last thing I am still slightly unsure of, referring back to your explanation in #63, is where you say one should "replicate [each of your demographics] by the number of nodes." Maybe it is an obvious point, but what does that look like exactly? Why is the number of replications equal to the number of nodes?

**Comment by jeffgortmaker** [comment]
A quadrature rule gives weights and nodes that integrate over a distribution with some degree of accuracy. Let's say you use a 1-dimensional rule that gives you 5 rows of `weights` and `nodes0`. Then for each row in the above data, you'll replicate it 5 times, multiplying the demographic share by the new `weights`, and using `nodes0`.

The idea is just that you're assuming demographics and unobserved preferences are statistically independent, so when doing a weighted sum over all agents in the market (approximating an integral over the population of consumers), we can split up this integral into an integral over demographics, and for each demographic type, a sub-integral over unobserved preferences, hence why you need to replicate each demographic type by as many nodes as you're using in your quadrature rule (in the above example 5).

If you add more than a few dimensions of integration, or if you have continuous demographic variables, it may end up being easier/more computationally convenient to just use Monte Carlo sampling to construct your agent data rather than demographic shares and quadrature. Then for each market, you should pick a number of agents, say 1,000, set `weights` equal to 1 / 1,000, and draw 1,000 rows of agents as follows: (1) resample with replacement from the population of consumers and use their demographics, (2) draw from the distribution of unobserved heterogeneity (e.g. standard Normal), either with simple Monte Carlo draws, or (see our paper for discussion of this) our preferred scrambed Halton draws.

**Comment by ny1526** [comment]
Thank you for the very detailed explanation! This is tremendously helpful and I understand the procedure now.
