### ISSUE TITLE
Question: model with no endogenous variables?

### ISSUE THREAD

**Issue by ny1526** [jeffgortmaker/pyblp#130]
Hi Jeff,

I am trying to estimate a demand model with random coefficients where I am treating all the characteristics are exogenous. (This may be a naive assumption, but for now, I am going with it.) I don't have prices in my model, so I rename one of the variables arbitrarily to `prices` so that I can set up the `product_data` and run the solver.

However, I seem to be running into the same problem as #122, where I am stuck at the same initial sigma values, perhaps because the model is underidentified. Maybe I am understanding this incorrectly, but I think the model should be just-identified since I do not have any endogenous variables. But I am wondering if it runs into this issue because it thinks that my `prices` variable is endogenous and requires an instrument.

Am I understanding this correctly? Is there a way to set up the problem so that all variables are considered exogenous?

Thanks again for your help.

**Comment by jeffgortmaker** [comment]
Right, so it's dropping the variable that you call ``prices`` from the set of instruments because it thinks it's endogenous. An easier thing to do is set ``add_exogenous=False`` and manually specific your full set of instruments in ``demand_instruments0``, ``demand_instruments1``, etc. Usually PyBLP just adds the non-price variables in X1 to this list.

**Comment by ny1526** [comment]
Ah got it, I didn't see the `add_exogenous` option. That works now, thank you!
