### ISSUE TITLE
Unable to do parallel processing with micromoments

### ISSUE THREAD

**Issue by giheungkim** [jeffgortmaker/pyblp#137]
Thank you for developing this amazing library.

I noticed that I cannot call .solve() method with pyblp.parallel() - it says it cannot pickle lambda functions, which is used to compute micro moments.

With some Googling, I found out that one of the limitation of pickle is that it is not compatible with lambda object multiprocessing. Someone developed "dill" package to remedy this issue: https://towardsdatascience.com/multiprocessing-and-pickle-how-to-easily-fix-that-6f7e55dee29d

Would it be difficult to switch out pickle with dill when there is micromoments involved? Thank you in advance.

**Comment by jeffgortmaker** [comment]
I think the following error message should have shown up in your full traceback?

https://github.com/jeffgortmaker/pyblp/blob/31a0f9304a3412548f7ce1a1ba7cfdf29c0d4747/pyblp/utilities/basics.py#L131-L134

Let me know if it didn't show up for some reason. The solution is to set `use_pathos=True` (and to [install it](https://pypi.org/project/pathos/)) which in turn uses dill.

**Comment by giheungkim** [comment]
Hi Jeff,

For now, I've found a workaround of just defining my own functions using the "def function_name(t,p,a): ..." syntex for compute_weights, compute_values, compute_value, and compute_gradient arguments for relevant Micromoment objects.

Without any lambda expressions, the default multiprocess goes through, and seems to be utilizing most of the initiated cores.

**Comment by jeffgortmaker** [comment]
Your minor issue seems like missing import in your code? The top of the traceback is `NameError: name 'np' is not defined` in a local file.

I'm not sure why you're having trouble with pathos. My parallel implementation uses either `multiprocessing.pool.Pool.imap_unordered` or `pathos.multiprocessing.ProcessPool.uimap`, depending on whether or not pathos is being used. My guess is any differences come down to different behavior (e.g., in iterated calls?) of these two methods, but I'd have to take a look at a minimum working example that tries to replicate the behavior you're seeing.

Since you've found a workaround I'll close this issue for now, but feel free to keep commenting if you end up putting together a minimum working example (i.e., just a few lines of code, ideally just comparing these above two methods) of the weird pathos behavior!

**Comment by giheungkim** [comment]
The problem with "NameError: name 'np' is not defined" was that numpy was not shared across process that pathos created even if it was imported in the main code. So it required importing numpy within the custom functions I wrote for weights and values computation.
