### ISSUE TITLE
Definition of aggregate elasticity and the measure reported by pyBLP

### ISSUE THREAD

**Issue by giheungkim** [jeffgortmaker/pyblp#162]
Hi Jeff,

I wanted to ask you a clarifying question.

In pyBLP implementation, the computation of the aggregate elasticities seems to be the aggregate change in market shares of inside goods upon receiving some uniform `factor` price increase.

If we want to convert this to percentage term, (i.e. 1% increase in market-level prices leads to X% decrease in inside good shares), shouldn't we multiply the pyBLP measure by (avg(p) of the market)/(inside good share of the market)?

I see some papers reporting pyBLP's measure of "aggregate elasticity" instead of the above. Could you help me understand what I might be missing?

**Comment by jeffgortmaker** [comment]
It depends on what you want to measure! I don't think you want to scale by the average price, since my reading of the PyBLP measure (it's been a while since I coded it up) is it already scales prices by a percentage factor. But scaling by the old inside share might be sensible, depending on what you're after.

My sense is that people use a few different definitions (for better or worse) for these types of things (@chrisconlon might be able to confirm), so it is best to be explicit about what you're computing. For example, having an explicit expression like the one given in PyBLP at least means we know what we're looking at, even if it's not what you're actually after.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open/keep commenting if you had more!
