### ISSUE TITLE
Trouble simulating fake data

### ISSUE THREAD

**Issue by khakieconomics** [jeffgortmaker/pyblp#31]
Hi Jeff, 

Love the package. But having some trouble simulating fake data when the dimensions of the random effects are large. Not sure precisely what's going on, but I do know that from my own function to find the equilibrium price/shares it can be sensitive to parameters. Any tips? 

```

import pyblp
import numpy as np
import pandas as pd

pyblp.options.digits = 2
pyblp.options.verbose = False
pyblp.__version__

id_data = pyblp.build_id_data(T=50, J=20, F=10)
integration = pyblp.Integration('product', 9)
simulation = pyblp.Simulation(
   product_formulations=(
       pyblp.Formulation('0 + prices + x1 + x2 + x3 + x4 + x5 + x6'),
       pyblp.Formulation('0 + prices + x1 + x2 + x3 + x4 + x5 + x6'),
       pyblp.Formulation('1 + x1 + x2 + x3 + x4 + x5 + x6 + z1 + z2 + z3')
   ),
   beta=[-2, 2, 1, -1, 1, -1, 1],
   sigma=np.diag([0.4, 0.3, 0.5, 0.3, 0.2, 0.7, 0.8]),
   gamma=[5, 1, -1, 1, -1, 1, -1, 1, -1, 1],
   product_data=id_data,
   integration=integration,
   seed=0
)

```

**Comment by jeffgortmaker** [comment]
So I don't think the issue here is with solving for equilibrium prices/shares -- that happens in `Simulation.solve`. I think the problem is that this configuration requires simulating 9^7 ~= 5 million individuals in each market, which is computationally intensive.

If your machine has enough memory this simulation should work fine, although it will take a while to solve it. It seems to work fine after reducing the level of the product rule to a number smaller than 9.

For now, if speed/memory are concerns, I'd recommend simulating fewer individuals in each market. Another typical recommendation for high-dimensional integration is to use sparse grids instead of simple product rules.

Reducing memory usage when individuals are the same in each market (e.g., when using quadrature) has been on my to-do list for a while now. I've been putting it off because allowing people to specify the same set of individuals for all markets will complicate the interface for specifying demographics, etc. But I'll probably end up improving this in the next couple package versions.

**Comment by chrisconlon** [comment]
I was able to solve this on my laptop without any trouble by switching "product" to "grid".
