### ISSUE TITLE
Knitro 12 support

### ISSUE THREAD

**Issue by kw468** [jeffgortmaker/pyblp#33]
Knitro 12 doesn't include knitroNumPy but here are two options:
(1) Instead of importing knitroNumPy, import knitro.numpy as knp in pyblp/configurations/optimization.py (lines 231-238 are no longer needed),
(2) import knitroNumPy for Knitro 11, which is compatible with Knitro 12.

**Comment by jeffgortmaker** [comment]
Thanks. I don't have access to a machine with version 12 yet, so implementing your suggestions is difficult at the moment.

Lines 231-238 are still needed for older versions because those directories often aren't included in (python) paths. Do those directories no longer exist in Knitro 12? Or have they changed?

[This page](https://www.artelys.com/docs/knitro/2_userGuide/otherProgInterfaces.html#pythoninterface) made it seem as though knitroNumPy still exists somewhere in Knitro 12. Has it been renamed as another file or something?

I'm also happy to accept a pull request if you find something that works for Knitro 12 (and doesn't impact behavior for older Knitro versions).

**Comment by kw468** [comment]
knitroNumPy is now in examples/Python/build/lib/knitro/numpy instead of examples/Python. Version 12 also calls a wrapper and ktr to verify license and for backwards compatibility. Simplest solution may be an if/else on knitro.__version__ to load knitro.numpy or knitroNumPy.

I'll report back on other alternatives if I can find one.

Thanks!

**Comment by jeffgortmaker** [comment]
Got it. It'd be great if the only thing needed is an if/else.

If you have pytest installed,  `pytest tests/test_optimization.py` might be useful here to make sure everything's running properly on your machine.
