### ISSUE TITLE
Collinearity issue in problem simulation when #(firms) = #(products)

### ISSUE THREAD

**Issue by dstackman** [jeffgortmaker/pyblp#35]
Hi Jeff, 

I'm running into a problem trying to simulate fake data when the number of firms is equal to the number of products (J=F). The following code snippet follows your [problem simulation tutorial](https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/simulation.html) exactly, except J=10, instead of J=20.

```
# Build market and firm IDs
id_data = pyblp.build_id_data(T=50, J=10, F=10)

# Specify integration rule
integration = pyblp.Integration('product', 9)
integration

# Set parameters for simulated data
simulation = pyblp.Simulation(
   product_formulations=(
       pyblp.Formulation('1 + prices + x'),
       pyblp.Formulation('0 + x'),
       pyblp.Formulation('0 + x + z')
   ),
   beta=[1, -2, 2],
   sigma=1,
   gamma=[1, 4],
   product_data=id_data,
   integration=integration,
   seed=0
)
simulation

# Simulate data from the model
simulation_results = simulation.solve()
product_data = simulation_results.product_data
simulation_results
# Set up and solve the BLP problem with pyBLP
problem = simulation_results.to_problem()
```

Running this code returns an error:

> ValueError: Detected collinearity issues with [demand_instruments0] and at least one other column in ZD. To disable collinearity checks, set options.collinear_atol = options.collinear_rtol = 0.

Disabling collinearity checks seems to work, (problem.solve runs and recovers the true parameter estimates), but I guess there should be something under the hood that prevents this error from being thrown in the first place, since the package should be able to handle single-product firms. 

Thanks in advance, this package is a great service to everyone trying to do applied work in IO!

**Comment by jeffgortmaker** [comment]
Right, so this is an bug with the default (sums of characteristics) BLP instruments creating a bunch of zeros for the "rival" columns. This happens when, as you note, we're working with single-product firms.

With your current version of the package, you can override `product_data` in `simulation_results.to_problem()` by copying `simulation_results.product_data` and deleting those columns of zeros.

But an easier thing to do is to use the development version of the code (so clone this repo) where I've already fixed the problem. (I don't think I fixed it before the last package version, but if you're a version behind you can try updating the package with `pip` first.)

Simulation is a bit different in the dev code -- you'll have to use `simulation.replace_endogenous()` instead of `simulation.solve()`. Instruments are also constructed in `simulation_results.to_problem()`, and I actually talk a bit about this exact problem at the end of its [docstring](https://pyblp.readthedocs.io/en/latest/_api/pyblp.SimulationResults.to_problem.html).
