### ISSUE TITLE
BLP (1995) tutorial not working

### ISSUE THREAD

**Issue by YilunL** [jeffgortmaker/pyblp#37]
I'm trying to run the BLP tutorial without any modifications to the code from the documentation tutorial and I run into an error creating the "Problem" (looks like something with the costs_type argument). 
It runs if I remove costs_type = "log".

![image](https://user-images.githubusercontent.com/19861469/63299521-95c5d300-c29b-11e9-9cd6-068900dbc001.png)

I'm using numpy 1.17.0 and pandas 0.22.0

**Comment by jeffgortmaker** [comment]
Seems like you're looking at the development docs, but you're using the stable (i.e., installed with pip instead of cloning the repo) version of the package. I moved `costs_type' to `Problem` initialization from `Problem.solve` after releasing the last stable version of the package.

You can find the stable version of that page [here](https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/blp.html). Note the `stable` in the URL instead of `latest`. Does using the stable version of the docs (or switching over to the dev version of the package) fix your problem?

**Comment by YilunL** [comment]
Yes it works. Thanks!
