### ISSUE TITLE
Questions about the replication of nevo 2000

### ISSUE THREAD

**Issue by Alalalalaki** [jeffgortmaker/pyblp#39]
Hi, I read your paper and go through the tutorial. I have some questions mainly about the replication of Nevo 2000. As I only read very limited contents of the literature, I really hope some of these questions are not too innocent. 

1. Nevo 2000 suggest a minimum-distance procedure to identify the taste coefficients β when adding product fixed effect into the linear part. Do `pyblp` provide this function? I didn't find it in the tutorial and the taste coefficients are not reported. Also is it possible to output the taste coefficients for all i so that one can draw the distribution like the figure in Nevo 2000?
 
2. In your paper, you say the loose tolerances explain the discrepancy between your results and those originally reported by Nevo. However, I use another [blp code](https://github.com/daria-pus/BLP-Demand-Estimation) with a tolerance of 1e-7 and get almost the same result as yours. I think the results do seem better than the original, but the reason might be somehow different.

3. Under the IV strategy of Nevo, is it meaningful to add `market_ids` as a fixed effect additional to `product_ids`, especially under panel data with large t? I try `absorb='C(product_ids) + C(market_ids)'` in the Nevo case and the price coefficient α decreases from -63 to -38. If this is not a good choice, why? (Sorry this question is completely due to the fact that I haven't fully understand the IV strategy of exploiting panel data.)

4. I notice that in the paper you specify price elasticity α as a part of parameter θ2 that enter non-linear part. It looks like somehow confusing because the estimated α in non-linear estimation should be some deviation and we still need to estimate α in the linear part. In other words, price is nothing different from other product characteristics except it always differs across markets. Is my understanding correct or do I miss something?

Thanks.

**Comment by chrisconlon** [comment]
Thanks for your interest.

1. This is just a linear IV GMM regression of the product fixed effects on the product characteristics. I don't think we do this now but it would straightforward to add.

2. The original public Nevo code didn't use a fixed tolerance and had a looser tolerance in both the inner loop (fixed point for delta) and the outer loop (nonlinear search for random coefficients).  It is a little hard to compare tolerances for the nonlinear part because Matlab reports them differently than Scipy does (I think Jeff can confirm this).

3. Sure you could do this.  pyBLP will let you for sure -- you do need to be a little careful that when you have both product and market fixed effects that you have some residual variation in your instruments.  Often instruments vary across products or over time, but we dont always have product and time specific variation in one instrument. Obviously without any residual variation -- after we demean the instrument we might be left with a vector of zeros.

4. We treat the price coefficient as part of theta_2 because we group all of the parameters on endogenous variables together. This is helpful for constructing the high dimensional fixed effects and in setting up the simultaneous supply and demand model. For demand only without fixed effects you are correct that we could treat this like any other parameter which linearly enters the function for delta_jt.

**Comment by jeffgortmaker** [comment]
Re 2: Yeah, I'm guessing that other implementation uses a slightly different termination condition, such as a relative one or one with a different norm that ends up being more restrictive even with a relatively "high" tolerance.

**Comment by Alalalalaki** [comment]
Thanks for fast reply. The explanation on the limitation of IV helps me a lot.
