### ISSUE TITLE
Multi Level nested logit.

### ISSUE THREAD

**Issue by RyanPiao** [jeffgortmaker/pyblp#44]
Hi, thank for your awesome project.
I have a question about the how to setup a multiple levels of nest, it seems like only support one layer of nest.

Thanks in advance.

**Comment by yirsung** [comment]
For example, I would like to have a rho for "mushy" and "nonmushy" and second layer for "sweet" and "unsweetened"? Is this possible?

**Comment by jeffgortmaker** [comment]
You're right that pyblp doesn't currently support the three-level nested logit you're describing (choices over the nest, subneset, and alternatives). I haven't implemented variations on the nested logit model (except for including random coefficients) because my focus has been on RC-based variants.

There are a lot of nested logit variants and implementing them isn't high up on my to-do list. Expressions for derivatives get messy and my understanding is that literature has to some extent moved more towards RCs. But I'm happy to accept contributions!

I'll keep this issue open as a possible future enhancement to the package.

**Comment by chrisconlon** [comment]
I think most people would prefer to estimate a joint distribution of random coefficients for "sweet" and "mushy" in this case. Otherwise you have to take a stand on whether consumers choose "sweet" first and then "mushy" or the other way around.

In principle I think this would be straightforward because the resulting estimator is linear in parameters.

There are other models of partially overlapping nests that are a bit more involved.

Is there a particular example with aggregate data you were thinking of? There seem to be a lot of variants out there and nothing I would call the "standard" version.

**Comment by yirsung** [comment]
Dear Jeff and Chris:
Thanks for the quick reply, I'm currently trying to do an RCNL on the smartphone market. I thought about to divide the smartphone into 3 groups(low, mid, high ends), and a subgroup of (iOS, Android).

If there is a strong in-group preference among iOS users (or Android), then it is important to implementing RCNL in that case.

 So far,  I have run an RCNL base on just one layer(iOS, Android), and it is significantly different from the RC model with the random coefficient on iOS.

I was wondering, what would the substitution pattern looks like if I implemented multilevel RCNL.

Thanks for your response. You guys are awesome.

**Comment by chrisconlon** [comment]
Sorry-- I missed this thread.

It seems like most people would want to estimate random coefficients here.

A random coefficient on the IOS or Android dummy and another random
coefficient on either a continuous measure of "quality" or on some "segment
dummies".

Otherwise you need to take a stand on whether consumers choose "OS first"
or "quality segment first".

Presumably a better model would allow correlation in the taste
parameters on OS and quality (maybe IOS users are more quality sensitive,
etc.).

The main advantage of nested logit specifications is that they can be
estimated with simple linear IV. However the point of pyBLP is to make more
complicated random coefficients specifications just as easy to estimate!

-Chris

**Comment by jeffgortmaker** [comment]
Cleaning up issues, multi-level nested logit isn't something we've had much demand for, and it'd be pretty difficult to implement. So I'm closing this for now.
