### ISSUE TITLE
Check that integration weights add to one (Simulation)

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#55]
Simulation results can give nonsensical shares if the `weights` column in `agent_data` isn't normalized to add to one within each market. GIGO, I know, but it's a relatively easy mistake to make. Would it be feasible/sensible to add a check when the simulation is initiated?

Reproducible example:
````
import pyblp
import numpy as np
import pandas as pd
agent_data_new = pyblp.build_integration(
    pyblp.Integration('monte_carlo', size=100), 2)
nodes = pd.DataFrame(agent_data_new.nodes)
weights = pd.DataFrame(agent_data_new.weights + 1) # where the weights are distorted
nodes.columns = ['nodes' + str(col) for col in nodes.columns]
weights.columns = ['weights']
agent_data_a = pd.concat([weights, nodes], axis=1)
agent_data_a['market_ids'] = 'market'
product_data = pd.DataFrame.from_dict(
    {'market_ids': {0: 'market'}, 'firm_ids': {0: 'firm'},
     'prices': {0: 1}, 'shares': {0: 0.5}})
test_sim = pyblp.Simulation(product_formulations=(
    pyblp.Formulation('0 + prices'), pyblp.Formulation('0 + prices')),
                            product_data=product_data,
                            agent_formulation=pyblp.Formulation('1'),
                            agent_data=agent_data_a,
                            beta=-1, sigma=1, pi=1, xi=0)
test = test_sim.replace_endogenous(prices=product_data['prices'],
                                   costs=np.zeros(len(product_data.index)),
                                   iteration=pyblp.Iteration('return'))
````

Then `test.product_data['shares']` gives a nonsense value (around 50).

**Comment by jeffgortmaker** [comment]
So a while ago I had the same thought as you and actually added this check in 2ae6c90.

I ended up reverting it in a future commit because although in the majority of circumstances you for sure want your integration weights to sum to one, this isn't always the case. In particular, this isn't the case after [importance sampling](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ProblemResults.importance_sampling.html). In this scenario, weights shouldn't be [too far from one](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ImportanceSamplingResults.html#pyblp.ImportanceSamplingResults.weight_sums), but I didn't want an exception to be raised when weights from procedures like this were being used.

But in retrospect I do think that adding a warning wouldn't be so bad, so I'll leave this issue open as a reminder. Thanks!
