### ISSUE TITLE
Some examples don't converge

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#56]
This may very well be correct, but I find it puzzling. Using all the defaults, when I run the example notebooks:

- After running `blp.ipynb`, `results.converged` is False
- After running `nevo.ipynb`, `results1.converged`, `results2.converged`, and `nevo_results.converged` are all False. In addition, `np.all(nevo_results.fp_converged)` is False.

[My replication notebooks are here](https://github.com/fpinter/pyblp-examples); note that some of my results differed from the originals (though I don't know exactly why).

I'm not sure why this is happening, and I'm not sure how to access the optimizer diagnostics in order to figure out why. Are the examples running as they're supposed to? Is this a problem with my configuration? (I'm using pyblp 0.9.0 and scipy 1.4.1.)

(cc'ing @saraharmitage, who pointed this out to me)

**Comment by jeffgortmaker** [comment]
Yeah, we really need to finish updating the tutorials at some point. You shouldn't be that concerned that they're giving some wonky results. Back when writing them, we were more focused on demonstrating how to use the API than anything else.

One issue is that the example datasets people are familiar with (automobiles and fake cereal) aren't exactly the "best" example problems that one could hope for, especially when we modify them to demonstrate something from the API that differs from the original paper's configuration.

Thanks for the replication notebooks. I'll refer to those when I get around to updating the tutorials. Until then, here's a few notes that might be helpful:

1. You might want to check out the dev code instead of the stable version (until I release a new stable version). In particular, the new `shares_bounds` argument in `Problem.solve` helps with non-convergence issues when using sparse grids in the Nevo example problem.
2. You also might want to use the configurations in Figures 5 and 6 in our companion paper (I'll update the tutorials to match these). We spent more time making sure that they actually worked decently. E.g. some of the default tolerances that show up in the (non-updated) tutorials might be too tight.
3. Try getting rid of the `pyblp.options.verbose = False` at the top of your notebooks. Seeing iteration progress will give you a better sense of what's going on. I have that there so that the notebooks aren't filled with volumes of iteration statistics.
4. Try setting `universal_display=False` in your `pyblp.Optimization(...)` configuration. This will show the default optimizer's information about convergence/progress/etc instead of pyblp's universal one, which might give a bit more information.
5. Even in a problem that converges, I wouldn't always expect `ProblemResults.fp_converged` to be all `True`. Sometimes the optimizer tries out a crazy parameter value, which creates some instability issues, preventing the fixed point routine from converging during that iteration. However, we would hope that the last column in `fp_converged` should be all `True`, since that column corresponds to the last optimization iteration (see [here](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ProblemResults.html#pyblp.ProblemResults.fp_converged)).

**Comment by fpinter** [comment]
Thanks! I updated the notebooks to reflect 3–5, and I'll take a closer look at 1 and 2.
3. Interestingly the one that converges (`results3` in Nevo) didn't converge in the first GMM step, but did in the second.
5. Yes, the last column is all True, fortunately.
