### ISSUE TITLE
Combining demographics with quadrature

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#63]
Is it possible to use demographics (e.g., income draws for `price/income` in the autos example) with a quadrature-based `Integration` configuration?

This question is inspired by the line in the autos tutorial:
> In non-example problems, it is usually a better idea to use many more draws, or a more sophisticated Integration configuration such as sparse grid quadrature.

If so, how would one do it?

**Comment by jeffgortmaker** [comment]
For sure. You have two options that I can think of, maybe @chrisconlon knows of others:

1. You may be willing to fit a normal or lognormal distribution to your demographic. In this case, you can transform one dimension of your quadrature-based nodes. For example, let's say you estimate the `mean` and `sd` of the log of income in your demographic data. Then you can simulate income in your model according to `exp(mean + sd * nodes)` where `nodes` are one dimension of the nodes you construct with your quadrature rule, e.g. via `pyblp.build_integration`.

2. If you aren't willing to fit such a distribution to your demographic (e.g. your demographic has a very non-normal distribution or is discrete), for each draw of your demographic, you can "replicate" that draw for as many nodes as there are in your quadrature rule. So if you draw one simulated individual with income $40,000, this same individual will show up as many times as there are nodes in your quadrature rule, once for each node of unobserved preference. Note that with this approach you'll have to be careful about re-normalizing your integration weights.

**Comment by chrisconlon** [comment]
Yes -- I have tried both.

1. BLP is a good example where they fit a lognormal distribution to income
and you could use draws from the quadrature points for the corresponding
lognormal. Income is lognormally distributed, and you want a coefficient on
1/income -- the rest of the coefficients are normally distributed. In this
case you could generate draws from a 6-d gaussian quadrature rule and just
transform one of them to 1/lognormal(Z) and use the other 5 sets of draws
for the "sigma" parameters. The advantage is that you'd have one set of
weights and could still exploit things like sparse grids to reduce the
burden.

2. I've also done #2. For example if you had households with and without
kids (like Nevo or Petrin). Then you need to do two steps as Jeff
described: 1) generate a set of quadrature rules for the normally
distributed unobserved heterogeneity and 2) generate draws from the other
distribution (ie: kids or no kids). This would be very easy because you
would just need Pr(Kids) and Pr(no kids) since there are two outcomes. But
then you would have to take the product rule of draws and weights (your
random normal draws x Kids/NoKids) and just use the regular quadrature
weights * p(kids) or p(no_kids).  The downside is you now need twice as
many draws. But the upside is that you added a dimension of heterogeneity
(and you only need twice as many draws not 10x as many!).
