### ISSUE TITLE
Complicated characteristic–demographic interactions

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#64]
In the autos tutorial, the BLP99 specification (where `j` indexes over products and `i` over agents)
````
u_ij = α_i * price_j / income_i + ... + ε_ij
````
is implemented by putting `prices` in X_2 and `I(1 / income)` in `agent_formulation`.

Is there any workaround which allows for more complicated interactions between demographic and product data? For example, the BLP95 specification
````
u_ij = α_i * log(income_i - price_j) + ... + ε_ij
````
or any other interaction which does not take a straightforward multiplicative form.

**Comment by jeffgortmaker** [comment]
At the moment, no, we don't support nontrivial functions of product characteristics and demographic interactions. We made this choice for three main reasons that I can remember:

1. Functions like the one from BLP95 can create difficult-to-diagnose numerical issues, like nonpositive arguments to logs.
2. They tend to be relatively ad-hoc and problem-specific, so it can be challenging to create a non-cluttered API for them.
3. Expressions for derivatives become more complicated.

I went maybe 1/3 of the way towards allowing for nontrivial interactions by supporting things like ``C(prices**2)`` and other nonlinear functions in patsy formulas. This required modifying the patsy interpreter so that it worked with SymPy to take derivatives of these expressions, which are needed for e.g. price elasticities.

But I stopped there because other features seemed more important. So for now you're probably stuck with doing something like estimating more parameters in a higher-order expansion of your nonlinear function.

But of course I'd be happy to talk about what would be needed to support more complicated specifications!

**Comment by fpinter** [comment]
Great, and thanks for the detailed explanation! I wanted to be sure I wasn't missing anything.

Just in case you were curious, the use case I actually had in mind is the following: if `d1_i` and `d2_i` are demographic variables and `x1_j` and `x2_j` are product characteristics, I wanted to estimate a single `β_i` in
````
u_ij = β_i * (d1_i * x1_j + d2_i * x2_j) + ... + ε_ij
````
The workaround I plan to use is to estimate two separate coefficients instead, `β1_i` and `β2_i`:
````
u_ij = β1_i * d1_i * x1_j + β2_i * d2_i * x2_j + ... + ε_ij
````

**Comment by jeffgortmaker** [comment]
Ah, I see, thanks for the example. At least during optimization, you could maybe implement your use case by creating a custom `Optimization` method that provides an interface to some routine with support for parameter constraints.

But you'd then have to do some more legwork to get correct standard errors and other post-estimation outputs. So I'm not sure that'd be worth the effort, especially since with your workaround you get a free test of the original assumption that beta1 = beta2.
