### ISSUE TITLE
Adding endogenous variable

### ISSUE THREAD

**Issue by polly93** [jeffgortmaker/pyblp#88]
Hello! Thanks for making the wonderful package for estimating the demand. I have a question about setting the model. 
Is there any way to add extra endogenous variable except 'prices'?
I want to set 'prices' and one variable as endogenous variables, but I cannot find the way to do.
Thank you.

**Comment by jeffgortmaker** [comment]
Yes, you can do this on the demand side. By default, `Problem` has `add_exogenous=True`, which will add all linear characteristics not involving price to the set of instruments. You'll want to set this to `False` and manually specify your *full* set of `demand_instruments` in `product_data`, which will include your excluded instruments (e.g. cost shifters, new instrument(s) for your extra endogenous variable, etc.), as well as exogenous characteristics in X1 (that previously were automatically added).

For more detail, e.g. about how this works with absorbed fixed effects, check out the [docs](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Problem.html#pyblp.Problem) for `product_formulations` and `add_exogenous`.

If you're approximating the optimal IVs with `ProblemResults.compute_optimal_instruments`, you'll also have to be careful to override a similar default in `OptimalInstrumentResults.to_problem`. Also note that all supply-side functionality in the package assumes that the only endogenous characteristic is price, so if you're interested in supply-side results, you may have to code those up yourself, depending on your application.

**Comment by polly93** [comment]
Sorry for late reply. Thank you for answering my question!! It helps a lot!!

**Comment by lc929** [comment]
@jeffgortmaker Hello Jeff, thanks so much for providing the wonderful public good and answering questions! 

I have a quick clarification question about how to deal with fixed effects when there is more than one endogenous variable: 

I now have prices and another endogenous variable x, as well as high-dimensional fixed effects. After I set add_exogenous = False, according to the tutorial, I have to manually absorb the fixed effects using build_matrix(). My understanding of the protocol is:
1. I use build_matrix() to get ``demeaned'' prices and x;
2. Still specify absorb() in the X1_formulation;
3. Feed ``demeaned'' prices and x to the pyblp.Problem, and set add_exogenous = False.

Is this the correct way of implementation?  Thanks so much!

**Comment by jeffgortmaker** [comment]
Almost! The one thing you have to manually demean are instruments, since you're setting `add_exogenous = False`, and they won't be automatically demeaned. Standard product characteristics (e.g. in the X1 formulation) will be demeaned as needed. So the protocol is:

1. Use `build_matrix` to get demeaned `demand_instruments` (both exogenous characteristics and excluded instruments).
2. Still specify `absorb` in the X1 formulation and feed non-demeaned characteristics into the `Problem`.
3. Set `add_exogenous = False` and feed the full set of demeaned `demand_instruments` (not just the excluded ones) into the `Problem`.

Does that make sense?

**Comment by lc929** [comment]
Awesome! Thanks so much for the very quick response!!!

**Comment by flucoe** [comment]
@jeffgortmaker I'm sorry to comment on a closed issue but I'm having trouble replicating the "automatic" implementation of pyblp using `build_matrix`. I'm doing this using one endogenous variable before I add a second one, to make sure that I'm doing this correctly.

1. If only `prices` are endogenous, I first use `build_matrix` to get demeaned `prices` and `demand_instruments`. To do this, I use `bf = pyblp.Formulation('0 + prices + demand_instruments0 + demand_instruments1 + ...,absorb='C(market) + C(time_ids) + C(product_ids))` where I have omitted all the other demand instruments. After defining this formulation, I use it with `build_matrix` to generate the matrix of demeaned data `matrix = pyblp.build_matrix(bf, df_prod)`.
2.  I created a new dataframe with the demeaned data, the identifiers still needed, and shares.
```
demeaned_data = pd.DataFrame()
demeaned_data['prices'] = matrix[:,0]
demeaned_instruments = matrix[:,1:]
for k in range(20):
    demeaned_data[f'demand_instruments{k}'] = matrix[:,k]

demeaned_data['market'] = df_prod['market']
demeaned_data['market_ids'] = df_prod['market_ids']
demeaned_data['product_ids'] = df_prod['product_ids']
demeaned_data['time_ids'] = df_prod['time_ids']
demeaned_data['firm_ids'] = df_prod['firm_ids']
demeaned_data['shares'] = df_prod['shares']
```
3. Your last comment says to "Still specify `absorb` in the X1 formulation and feed non-demeaned characteristics into the `Problem`" So, this is what I did: `X1dm = pyblp.Formulation('0 + prices', absorb='C(market) + C(time_ids) + C(product_ids)')` and `form_hand = (X1dm, X2)` where `X2 = pyblp.Formulation('0 + prices')` is the same I defined when I used the default pyblp approach when dealing with a single endogenous variable.
4. Define the problem with non-demeaned data `problem_rep = pyblp.Problem(form_hand,df_prod,integration=h_integration, add_exogenous=False)`. However, I don't see how this uses demeaned prices and instruments.
5. Finally, you use `Problem` again in the last step of your explanation with the demeaned data but I don't see how this is connected with the previous step.

I'm sure I do not understand something in your explanation. Could you help me figure this out? Thanks!

**Comment by jeffgortmaker** [comment]
Okay so,

1 and 2. You only need to de-mean `demand_instruments`. Standard product characteristics like `prices` will be automatically de-meaned as needed. So `demeaned_data` should just have the original `prices`.

4 and 5. You should pass your modified `demeaned_data` to `Problem`, not your original `df_prod`.

**Comment by flucoe** [comment]
Thanks Jeff. I was able to replicate the point estimates but I keep having trouble with the standard errors. Specifically, I get `Detected that the estimated covariance matrix of aggregate GMM moments is singular with condition number +INF. To disable singularity checks, set options.singular_tol = numpy.inf.` but this doesn't happen when I don't do this "by hand." Any ideas what am I doing wrong/missing? Everything in the output looks the same (Objective Value, Projected Gradient Norm, Reduced Hessian Min/Max Eigenvalue, Clipped Shares, Weighting Matrix Condition Number), but for the Covariance Matrix Condition Number. Thanks.

**Comment by jeffgortmaker** [comment]
Huh, I'm not sure.

Can you compare various fields in `Problem.products`, e.g. `Problem.products.ZD`, too? Also `ProblemResults.xi`? Differences in those might give us a sense of what's going on. Also just problem configuration and results output for the two problems would be helfpul.

**Comment by markkaj** [comment]
This has been a super helpful thread! One clarifying question, though: what exactly should I take into account when calculating the optimal IVs when I have previously used the `add_exogenous = False` option (meaning there are more than one endogenous variable)?

**Comment by jeffgortmaker** [comment]
I'm guessing you've only specified a demand side? (I wouldn't even be sure how to interpret your estimates before thinking about optimal instruments if you also specified a supply side with an additional endogenous variable.)

In this case, you should take a careful look at the documentation for `OptimalInstrumentResults.to_problem`. Without a supply side, by default, the optimal IVs this constructs are typically (1) optimal IVs for nonlinear parameters, stacked with (2) optimal IVs for linear parameters, which are simply exogenous product characteristics and the `expected_prices` argument to `ProblemResults.compute_optimal_instruments`.

In your case, (1) is correct, but (2) will not be correct, since what you really want is to add additional `expected_x` columns for each additional endogenous variable `x` other than price. So what you should do is just construct your own updated `Problem` with `demand_instruments` equal to (1) `OptimalInstrumentResults.demand_instruments`, stacked with (2) exogenous product characteristics in X1 and estimates of `E[x | Z]` for each endogenous product characteristic in X1.

Does that help?

**Comment by markkaj** [comment]
Thanks Jeff, this definitely helps!
