### ISSUE TITLE
Objective function not minimized at true parameter value with simulation

### ISSUE THREAD

**Issue by avbra** [jeffgortmaker/pyblp#89]
Hello,

I am using the simulation feature to construct criterion functions used for testing new optimizing algorithms. However, when investigating a few simple configurations (single-dimensioned non-linear parameter), it seems that for quite a few configurations of firms and product numbers the minimum of the objective function is not even close to the true parameter value, and the resulting estimate is therefore highly biased. I am wondering if I have configured the simulation wrong? Admittedly I am quite new to the BLP model.

Here is an example of this happening:

```
import pyblp
import numpy as np

#Set seeds for reproducing
np.random.seed(0)
bound_width = 10

# SIMULATION OF DATA

# Define the market and sample sizes

T = 20
F = [2, 5, 10]
def num_products(F, J_F):
    tot_products = F*J_F
    return tot_products
J_F = [3, 4, 5]

FJ_combs = np.zeros((9, 2))

k = 0

for i in range(3):
    for j in range(3):
        FJ_combs[k][0] = int(F[j])
        FJ_combs[k][1] = int(num_products(FJ_combs[k][0], J_F[i]))
        k += 1

# build agents for individual characteristics

ids_data = list()

for i in range(9):
    ids_data.append(pyblp.build_id_data(T=T, J=int(FJ_combs[i][1]), F=int(FJ_combs[i][0])))

# Must specify xi as there are no supply side characteristics

xi_draws = list()

for i in range(9):
    xi_draws.append(np.random.uniform(0, 1, int(FJ_combs[i][1]*T)))

# simulate

integration = pyblp.Integration('monte_carlo', size=500, specification_options={'seed': 0})

simulations = list()

for i in range(9):
    simulations.append(pyblp.Simulation(
        product_formulations=(
            pyblp.Formulation('1 + prices + x'),
            pyblp.Formulation('0 + x'),
            ),
        beta=[1, -2, 2],
        sigma=2,
        xi = xi_draws[i],
        product_data=ids_data[i],
        integration=integration,
        seed=0
    ))

# Set some arbitrary cost level drawn from the Uniform Distribution

costs = list()

for i in range(9):
    costs.append(np.random.uniform(0, 1, int(FJ_combs[i][1]*T)))


# Make market shares and prices endogenous
simulation_results = list()

for i in range(9):
    simulation_results.append(simulations[i].replace_endogenous(costs[i]))

# Solve problem

problems = list()

for i in range(9):
    problems.append(simulation_results[i].to_problem())

#start-val
start_val = np.random.uniform(2-(2*bound_width), 2+(2*bound_width), 1)

results_CONV = list()

for i in range(9):
    print("Problem: ", i + 1)
    results_CONV.append(problems[i].solve(
        sigma=start_val,
        sigma_bounds = (2-(2*bound_width), 2+(2*bound_width)),
        beta_bounds= ([2-(1*bound_width), -2-(2*bound_width), 2-(2*bound_width)], [2+(1*bound_width), -2+(2*bound_width), 2+(2*bound_width)]),
        method = "1s",
        optimization=pyblp.Optimization('l-bfgs-b', {'gtol': 1e-5})))

result_sigmasCONV = list()

for i in range(9):
    result_sigmasCONV.append((results_CONV[i].parameters[0][0]))

print("results CONV", result_sigmasCONV)
```

The reported best estimates for the non-linear sigmas for each of the 9 configurations are:
results CONV [-2.2912868408492693, -1.6660175173709149, 1.7931875525387007, 1.9021884309117252, 2.0793411983428016, -2.124666999332383, 1.7747774201014022, -2.5843292304936423, -2.439579624790228]

**Comment by jeffgortmaker** [comment]
Actually I think this is working pretty well, although it might not be obvious at first glance!

Your estimates for sigma are all pretty close to the true value of 2 in absolute value. Note that as a scalar, sigma will be squared to get the variance of the random coefficient, so in theory its sign doesn't matter (although depending on the integration rule you use it may matter a bit numerically). In practice, you'd usually want to bound sigma from below by zero so that you don't have two global optima (at positive and negative values of sigma). You're getting negative estimates because your starting value with this seed is around -3.

Even then, your results are a bit off from 2 in absolute value because you don't have many observations with which to estimate the model (looks like between 100 and 700), and you have a good amount of noise in xi.

Perhaps the easiest way to get the near-2 results you're looking for is to
1. reduce the amount of noise in xi with `xi_draws.append(0.01 * np.random.uniform(0, 1, int(FJ_combs[i][1]*T)))`, and
2. use a positive starting value for sigma with `start_val = 1`.

A few other notes:
 - You don't need `beta_bounds` because the linear parameters are concentrated out of the problem, and don't need to be numerically optimized over.
 - It won't matter in a simple simulation like this, but my typical recommendation is to optimize 3-5 times from random starting values within your parameters' bounds, to verify that you get to the same global optimum.
 - If you're also trying to evaluate estimates for the coefficient on prices, you may want to include a cost shifter in your set of instruments. Right now you're just using the default ones constructed by `SimulationResults.to_problem`, which are pretty naive without a fully-specified supply side.

**Comment by avbra** [comment]
Thank you for your reply, makes sense now. Can I ask a few more questions:
Can I increase the simulated number of observations, but keep the number of markets, products, and firms the same?
For a customized optimization algorithm: is there a way to pass that there is an error when computing the objective function to the optimization routine? I see the error messages are printed, but cannot find a way to pass this directly when calling ```objective_function(theta)```.

Thanks again, this library has been immensely helpful!

**Comment by avbra** [comment]
Thanks, I mainly just need realistic objective function, so increasing the number of markets should be fine. Thanks! 
Apologies for not being clear: Getting the following error message made me think I can pass a constraint to my optimizer that only trial values that ensures non-negative market shares would be helpful:

At least one error was encountered. As long as the optimization routine does not get stuck at values of theta that give rise to errors, this is not necessarily a problem. If the errors persist or seem to be impacting the optimization results, consider setting an error punishment or following any of the other suggestions below:
The fixed point computation of delta failed to converge. This problem can sometimes be mitigated by increasing the maximum number of fixed point iterations, increasing the fixed point tolerance, choosing more reasonable initial parameter values, setting more conservative parameter or share bounds, or using different iteration or optimization configurations.
Encountered a numerical error when computing delta. This problem is often due to prior problems, overflow, or nonpositive shares, and can sometimes be mitigated by choosing smaller initial parameter values, setting more conservative bounds on parameters or shares, rescaling data, removing outliers, changing the floating point precision, or using different optimization, iteration, or integration configurations. Errors encountered: divide by zero.

Was therefore wondering if the iteration is accessible to the optimizer, so that if the market shares for certain trial values are negative they can be excluded from the considered domain?

**Comment by jeffgortmaker** [comment]
Right, so you can pass a custom [`Iteration`](https://pyblp.readthedocs.io/en/stable/) configuration to the `iteration` argument of `Problem.solve`, similar to the custom optimizer you were thinking of using.

But I think there's a good chance that you're running into the same problem as #85: the default SQUAREM fixed point iteration routine wasn't robust to an underflow problem until I (hopefully) fixed the issue in 6649932. The commit isn't included in a stable release yet, so you'd have to clone this repo and include its location in your `PYTHONPATH` environment variable until I release a new stable version. (Either that or use some other `iteration` routine like `'lm'` or `'simple'`).

Let me know if this solves the issue; otherwise we can debug. By default the `shares_bounds` argument to `Problem.solve` does pretty much what you're suggesting, bounding shares from below by a small number, so if you're not experiencing the same issue as #85, it's probably something else.

**Comment by avbra** [comment]
Great, using a different iteration routine fixed the issue with dividing by zero. However, still having issues that the iteration does not converge and therefore want to try using a custom ```Iteration``` method. What I am struggling with is to access the arguments that is passed to the custom iteration method within the custom optimization routine (so I can pass the infeasible regions out-of-bounds to the optimizer defined in the custom optimizer). Is there a way to access these arguments and passing them to the optimizer?

**Comment by jeffgortmaker** [comment]
There's no built-in way to communicate between them.

A (slightly hackish) way to do this is by setting [non-local](https://stackoverflow.com/questions/1261875/python-nonlocal-statement) variables (or something like that) in your custom iteration method that can then be accessed in your custom optimization method. You might want to reset these variables after using them in your optimization method before letting the routine move on to the next iteration. Does that make sense?

**Comment by avbra** [comment]
Yep, this works perfectly, thank you! I can only make it run the iteration from inside the optimization routine by calling the objective function, but thats fine. 

Thanks a lot for your help, and also big thanks for excellent documentation and tutorials!

**Comment by jeffgortmaker** [comment]
Great! I'm glad you're finding it useful.
