### ISSUE TITLE
Simulated prices using replace_endogenous is different from real data

### ISSUE THREAD

**Issue by yihao-yuan** [jeffgortmaker/pyblp#90]
Hi,

I am using ```simulation``` and ```replace_endogenous``` to compute prices. However, I found that they are different. Here are the codes:

```
# BLP estimation
X1_formulation = pyblp.Formulation('0 + prices', absorb='C(product_ids) + C(store_code_uc) + C(week_end)')
X2_formulation = pyblp.Formulation('1 + prices')
product_formulation = (X1_formulation, X2_formulation)
problem = pyblp.Problem(
    product_formulation,
    product_data = sales,
    agent_data = agent
)

results = problem.solve(
    sigma = np.diag([1,1]),
    method = '1s',
    optimization = pyblp.Optimization('simple')
)

# Compute xi (including FEs), marginal cost and consumer welfare
delta = results.compute_delta()
xi = delta - np.multiply(results.beta, np.asarray(sales.prices)).T
mc = results.compute_costs(firm_ids = sales.brand_code_uc)
cs = results.compute_consumer_surpluses()

# Use simulation to compute counterfactual
sales_cf = sales[['market_ids','brand_code_uc','product_ids']]
sales_cf = sales_cf.rename(columns = {'brand_code_uc':'firm_ids'})

cf = pyblp.Simulation(
    product_formulations = (pyblp.Formulation('0 + prices'), pyblp.Formulation('1 + prices')), 
    product_data = sales_cf, 
    beta = results.beta, 
    sigma = results.sigma, 
    agent_data = agent,
    xi = xi
)

cf = cf.replace_endogenous(costs = mc, error_behavior = 'warn')

# To compare with simulation results
cf_prices = results.compute_prices(costs = mc)
```

Both ```replace_endogenous``` and ```compute_prices``` triggered numerical warnings:
```
The fixed point computation of synthetic prices failed to converge. This problem can sometimes be mitigated by increasing the maximum number of fixed point iterations, increasing the fixed point tolerance, configuring other iteration settings, or making sure the specified parameters are reasonable. For example, the parameters on prices should generally imply a downward sloping demand curve.
```
However, ```cf_prices``` computed using ```compute_prices``` is very close to the true data, while ```cf[`prices']``` computed using ```replace_endogenous``` is very different. As far as I found, this difference only occurs when there are numerical problems with convergence of synthetic prices. When there are no warnings, both methods generate synthetic prices that are very close to the true data. 

Because eventually I want to compute counterfactual where a product ```j``` is removed from market, I think ```simulation``` would be preferred. However, the discrepancy between the two methods is concerning. Do you have any ideas on why this happens, and any suggestions on which method to use?

Thank you!

**Comment by jeffgortmaker** [comment]
To confirm, in your simulation the contributions of the estimated fixed effects are all in `xi`, right?

One thing that may explain the different results you're getting with `compute_prices` versus `replace_endogenous` is that as configured, the former by default starts the iteration routine at the prices in the data, while the latter (when a `prices` argument isn't set) starts at the specified `costs`. Since neither converges, I wouldn't expect them to return the same thing.

Here are some possibly useful things to try out:

 - Verify that you get the same (non-converged) results when you specify `prices=mc` for `replace_endogenous`.
 - Verify that the issue isn't just the fixed point solver you're using to solve for equilibrium prices by using a few different `Iteration` configurations. You may also want to try different starting values, e.g. randomly starting prices at 50% above and below the prices in the data or marginal costs (whatever seems more reasonable).
 - Run `compute_prices` market-by-market to see where the errors occur by specifying `market_id=problem.products.market_ids[i]` for `i` in the range of market ID indices.
 - If there are convergence issues in some markets and not in others, inspect your data to try to understand what's uniquely different in these markets.
 - If there are convergence issues in all markets, tweak the estimated parameter values in your simulation to see if the issue is that there is no equilibrium (or it is difficult to find) at your estimates.

If the issue isn't technical/numerical, but rather to do with existence of an equilibrium, I'm afraid I don't have great intuition for when one will exist in a general BLP-type problem. I'll refer you to footnote 61 in [our paper](https://jeffgortmaker.com/files/pyblp.pdf) where we cite some of the relevant literature, and in particular [Morrow and Skerlos (2010)](https://arxiv.org/abs/1012.5832) along with their more technical [2010](https://arxiv.org/abs/1012.5836) and [2011](https://pubsonline.informs.org/doi/abs/10.1287/opre.1100.0894?casa_token=YLYPdgsz11AAAAAA%3ATYPsrkyUQ_vRFQR6buu6SWAcumrU1EfgJIkn7he5jiPW3JkXs6Jkcmuk9-O-D2EzgAuuUpZ84HE_&) papers that we rely on for their fixed point approach.

When coding up BLP-type simulations in practice, I've found that the easiest way to set up a problem that delivers convergence problems is to have demand that doesn't slope sufficiently downward, i.e. having an estimated `beta` on prices in your problem that isn't sufficiently negative. (To check this theory, I'd see what happens when you make your `beta` more negative in your simulation.) Once you put a random coefficient on prices, you have to start thinking about the slope of demand for different heterogenous agents as well, and the demand of those agents.

**Comment by yihao-yuan** [comment]
Thank you, Jeff. Yes, ```xi``` includes the fixed effects. I am still confused by how ```replace_endogenous``` works—it computes counterfactuals market-by-market, right? However, I found that when I use a small fraction of markets in my data to compute "counterfactuals" and compare them with the true data, ```replace_endogenous``` recovers true prices and market shares perfectly. However, once there is any warning, everything is wrong, including the market that worked above. I do not understand why this happens—I thought for the same market, whatever the other markets are, as long as ```pyblp.Simulation``` and ```costs``` specified in ```replace_endogenous``` are the same, the counterfactual results should be the same?

**Comment by jeffgortmaker** [comment]
Yes, it computes counterfactuals market-by-market in a loop. I'm not sure why an error in one market would bleed over into the others -- I'd have to see a minimum working example of that happening to help debug.

**Comment by yihao-yuan** [comment]
Hi Jeff, sorry for the late response. I think I figure out what's going on in my code. Sorry for the confusions—it's because I'm very new to python, and don't know that a change to the copied list will change the referenced list. After I figured out the problem, your package worked like a charm. Thanks a lot!

**Comment by jeffgortmaker** [comment]
Glad to hear it!
