### ISSUE TITLE
Beta Estimates for Sugar, Mushy and Constant

### ISSUE THREAD

**Issue by RoboDel2020** [jeffgortmaker/pyblp#93]
Hi,

The package is really great.

However when I am following the tutorial of Nevo'a cereal data https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/nevo.html

I get the beta estimate only for the price. In his paper, he has beta estimates also for Sugar, Mushy, and Constant. 
<img width="617" alt="Screen Shot 2021-07-22 at 7 19 51 PM" src="https://user-images.githubusercontent.com/68827065/126725881-078f4dbb-875c-4df3-a3d7-d16a23bb1f8e.png">

How can I get them?

Thank you

**Comment by chrisconlon** [comment]
As is the case in the paper -- you need to regress the estimated d_jt's
(product fixed effects) on the characteristics (including the appropriate
minimum distance weights) and IV's.

Since this is just a regression -- PyBLP doesn't need to do anything.

Though perhaps we should add an example like this to the notebook?

**Comment by jeffgortmaker** [comment]
Yeah, this seems like a pretty common question. Contributions to the [notebook](https://github.com/jeffgortmaker/pyblp/blob/master/docs/notebooks/tutorial/nevo.ipynb) are of course welcome if you end up implementing the regression!

**Comment by RoboDel2020** [comment]
I tried to follow your hint, but could not figure it out. If it is not too much time-consuming, can you update that part in the notebook? Thank you.

**Comment by RoboDel2020** [comment]
Great, Works
