### ISSUE TITLE
Solving equilibrium price in Section 3.7 in the manual

### ISSUE THREAD

**Issue by yutatoyama** [jeffgortmaker/pyblp#94]
This is a minor point, but I was wondering whether equation (3.44) in Section 3.7 of the manual may have a typo. Specifically, I think there is no need to take a transpose of the matrix given the definition of $\Lambda$ and $Gamma$ in (3.45) and (3.46). (see the highlight in the attached screenshot). 
The equation without transpose seems consistent with equation (27) in the original pyBLP paper.

![ScreenShot_EqPrice](https://user-images.githubusercontent.com/9499632/127471447-b6f30548-3c16-456b-954f-fb0f6c2944c1.png)

**Comment by jeffgortmaker** [comment]
Thanks for noticing the discrepancy! It's a minor point, but possibly an important one for cases where prices enter nonlinearly into utility.

As written in the paper, Gamma is symmetric because we call dU_ijt / dp_jt = alpha_i, and don't explicitly consider the more general case in the documentation. Unless @chrisconlon can think of a reason why ownership matrices might be non-symmetric, it shouldn't matter whether there's a transpose or not for most cases.

But if dU_ijt / dp_jt *does* depend on j (for example, if prices enter nonlinearly into utility), then I think this may be a bug. I'll have to look through our expressions to make sure.

**Comment by chrisconlon** [comment]
Yes. The common ownership paper involves cases where A might place a weight
of 0.7 on B's profit, but B might place a weight of 0.2 on A's.

The "typical IO" case is that the weights are always 0/1 and symmetric --
but more and more people are allowing for asymmetries (and partial profit
weights).

-Chris

**Comment by jeffgortmaker** [comment]
So with that in mind, we probably should have added a transpose to the expression in our paper if it were for nontraditional ownership matrices.

The expression in the docs lines up with that in Morrow-Skerlos 2010, with the exception of (3.46) where dU_ijt / dp_jt should be dU_ikt / dp_kt. It seems like this is just a type, which isn't reflected in our code, where I'm pretty sure Gamma is computed correctly (and tested with finite differences in a nonlinear prices specification when it's also used for computing elasticities).

Thanks again for noticing this -- hopefully the lack of a transpose in the paper doesn't cause too much confusion going forward.

**Comment by yutatoyama** [comment]
Thanks a lot for your quick response!
